### ISSUE TITLE
HH doesn't behave correctly

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/pynn_genn#22]
PyNN has a very limited description of the model here:
https://pynn.readthedocs.io/en/latest/standardmodels.html#hh-cond-exp

And currently GeNN implements it like this:
https://pynn.readthedocs.io/en/latest/standardmodels.html#hh-cond-exp

I'm assuming Anton used the standard GeNN model as a reference but I remember you saying something about there being a copy-paste error in it.

![pynn_hh](https://user-images.githubusercontent.com/6793242/48196077-5603af80-e349-11e8-9458-d52cec9daefb.png)

**Comment by neworderofjamie** [comment]
The PyNN interface automatically figures out which PyNN parameters need to be implemented as GeNN parameters or variables (as they can have different values across the population) so all the models are specified within PyGeNN. In short, make your HH modifications here https://github.com/genn-team/pynn_genn/blob/master/pynn_genn/standardmodels/cells.py#L378-L455

**Comment by tnowotny** [comment]
Just pushed an updated model to the new fixed_TraubMiles branch. Unfortunately, I was unable to test it as the installer got itself into a knot of python dependencies, ending with the error
```error: numpy 1.8.0rc1 is installed but numpy>=1.8 is required by set(['lazyarray'])```
which I do not understand as 1.8.0rc1 seems >= 1.8?

**Comment by neworderofjamie** [comment]
I guess 1.8.0rc1 is a pre-release version of 1.8 (which is in itself very
old) so it is older than 1.8 by some definition...

**Comment by tnowotny** [comment]
Unrelatedly - when following the install instructions for pynn_genn I noticed that the genn library generated ended in ```.so``` rather than in ```.dylib``` and I used this command:
```
"@loader_path/libgenn_CPU_ONLY_DYNAMIC.dylib" pygenn/genn_wrapper/libgenn_CPU_ONLY_DYNAMIC.so
```

**Comment by tnowotny** [comment]
Hum ... but I am not sure how I can upgrade ... pip refuses as the original Python was installed by "distutils":
```
Cannot uninstall 'numpy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by tnowotny** [comment]
> I guess 1.8.0rc1 is a pre-release version of 1.8 (which is in itself very old) so it is older than 1.8 by some definition...

ah ... right ... I should have known that "rc" is "release candidate" ...

**Comment by tnowotny** [comment]
ok ... easy_install seems to have done the trick for upgrading numpy.
But now I get this:
```
m900789:system tn41$ python test_genn.py 
Traceback (most recent call last):
  File "test_genn.py", line 2, in <module>
    from .scenarios.registry import registry
ValueError: Attempted relative import in non-package
```

**Comment by neworderofjamie** [comment]
If you were on the python_wrapper branch **and** you set the DYNAMIC=1 option it should have created a dylib

**Comment by neworderofjamie** [comment]
for some reason the 'nose' testing framework PyNN uses does not make it that easy. From ``pynn_genn/test/system/`` what you have to do is ``nosetests --tc=testName:test_HH_cond_exp test_genn.py``

**Comment by neworderofjamie** [comment]
It passes for me though :)

**Comment by tnowotny** [comment]
ok ... true. After that we are getting there but:
```
m900789:system tn41$ nosetests --tc=testName:test_HH_cond_exp test_genn.py
c++ -shared -fPIC -DCPU_ONLY -std=c++11 -MMD -MP  -I"/its/home/tn41/localdisk_projects/develop/genn//lib/include" /its/home/tn41/localdisk_projects/develop/genn//lib/src/sparseUtils.cc runner.cc -o librunner.so
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found
Abort trap: 6
```

**Comment by neworderofjamie** [comment]
Can you try adding ``cpu_only=True`` to the call to sim.setup here https://github.com/genn-team/pynn_genn/blob/master/test/system/scenarios/test_cell_types.py#L42

**Comment by tnowotny** [comment]
Yes! That has done it. It ran the test successfully on my Mac. Well done.

**Comment by neworderofjamie** [comment]
Ok great! Now just to figure out what's broken with the tests...

**Comment by tnowotny** [comment]
The HH was easy ... if you have others of similar flavour, feel free to assign me some. If it's deep in the python wrapper, I won't be able to help as you know.

**Comment by tnowotny** [comment]
One more comment before I forget: NEST did detect spikes at >= -33 mV which I thought was a bit early/low but I have for now implemented it this way as well.
