### ISSUE TITLE
deprecated function call (add_extra_global_param)

### ISSUE THREAD

**Issue by chanokin** [genn-team/pynn_genn#46]
The following lines use a deprecated function call, they should be changed to `set_extra_global_param`

https://github.com/genn-team/pynn_genn/blob/0774e22ef99c11325befe05f2dd7072b30e60693/pynn_genn/populations.py#L145

https://github.com/genn-team/pynn_genn/blob/0774e22ef99c11325befe05f2dd7072b30e60693/pynn_genn/populations.py#L183

**Comment by neworderofjamie** [comment]
Sorry about this - @jamesturner246 and myself wanted to start tidying up the somewhat adhoc PyGeNN API
