### ISSUE TITLE
counter reset for DCSource

### ISSUE THREAD

**Issue by koch-r** [genn-team/pynn_genn#58]
The issue with the counter reset for the `reuse_genn_model` flag (#57 ) also exists for DCSources.
I created a [minimal example](https://gist.github.com/koch-r/ac5f0ac419d06c81ef965a01d58c6dc0to ) to highlight the problem. When the `reuse_genn_model`  flag is used, the following error occurs:
```
'std::runtime_error'
  what():  Cannot find symbol 'applyIinjpopulation_1_AllCells_DCSource_0'
```

Analogously to the reset for popultations, the error goes away when `self.num_current_sources = 1`  is added to the `clear` function

**Comment by chanokin** [comment]
I can't find the minimal example or it's not public, but I'm assuming you:
1. set simulation up with a dc source and reuse model flag,
2. run and end simulation
3. set simulation up again
4. run

After the second run does the simulation break?

**Comment by koch-r** [comment]
> I can't find the minimal example or it's not public, but I'm assuming you:
> 
>     1. set simulation up with a dc source and reuse model flag,
> 
>     2. run and end simulation
> 
>     3. set simulation up again
> 
>     4. run
> 
> 
> After the second run does the simulation break?

Thank you for your fast reply. Yes that is exactly what the example did. I forgot to set it public, sorry for that.
